//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdenesTrabajo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        public decimal id_equipo { get; set; }
        public string tipo { get; set; }
        public string modelo { get; set; }
        public decimal serie_equipo { get; set; }
        public string discoduro { get; set; }
        public string estadoHDD { get; set; }
        public Nullable<decimal> serialRAM1 { get; set; }
        public Nullable<decimal> serialRAM2 { get; set; }
        public Nullable<decimal> serialCargador { get; set; }
        public Nullable<decimal> serialBateria { get; set; }
        public string observaciones { get; set; }
        public string estadoequipo { get; set; }
        public decimal id_orden_FK { get; set; }
    
        public virtual Orden Orden { get; set; }
    }
}
