//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdenesTrabajo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden_Seguimiento
    {
        public decimal id_seguimiento { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecharevision { get; set; }
        public decimal id_orden_FK { get; set; }
        public decimal id_usuario_FK { get; set; }
    
        public virtual Orden Orden { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
