//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdenesTrabajo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orden()
        {
            this.Equipo = new HashSet<Equipo>();
            this.Orden_Seguimiento = new HashSet<Orden_Seguimiento>();
        }
    
        public decimal id_orden { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public string observacionesrecibido { get; set; }
        public string diagnostico { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
        public string observacionesfinal { get; set; }
        public decimal id_usuario_FK { get; set; }
        public decimal id_cliente_FK { get; set; }
        public decimal id_estado_FK { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipo> Equipo { get; set; }
        public virtual Estado_Orden Estado_Orden { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orden_Seguimiento> Orden_Seguimiento { get; set; }
    }
}
